project:
  title: "ml-pres"

author: "Manuel DÃ¶mer"
organisationalunit: "Abteilung Angewandte Mathematik, Physik und Operations"


jupyter: python3
toc: true
number-sections: false

editor:
  render-on-save: true

format: 
  revealjs:
    theme: default
    transition: slide
    background-transition: fade
    highlight-style: github
    code-line-numbers: true
    fig-align: center
    mermaid:
      theme: default
    mermaid-format: png

    toc: false
    code-fold: true
    controls: false
    chalkboard: false
    from: markdown+emoji
    
    slide-number: true
    self-contained: false
    css: quarto_css/hscroll.css
    template-partials:
      - title-slide.html
    include-in-header: 
      text: |
        <style>
        .v-center-container {
          display: flex;
          justify-content: center;
          align-items: center;
          height: 90%;
        }
        </style>